# Generated by Django 3.2.3 on 2021-10-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
